### PR TITLE
Add E2E & benchmark actions

### PR DESCRIPTION
**Pull request by kinosang**
This PR add e2e tests and benchmark actions.

**Type of change**

* [x] New Feature (non-breaking change which adds functionality)

**Checklist**

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my own code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] My changes generate no new warnings
* [x] Any dependent changes have been merged and published in downstream modules
* [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by kinosang** [comment]
bors try

**Review by coderfengyun — APPROVED** [review]

**Pull request closed without merging**
